files:
mkdir -p ~/.config/aria2

"~/.config/aria2/aria2.session" file content   => nothing just empty file
==============
"~/.config/aria2/aria2.config" file content:

enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=true
rpc-secret=42821927
max-concurrent-downloads=5
max-connection-per-server=8
continue=true
dir=/home/wineo/dlmovies
split=8

log=/home/wineo/.config/aria2/aria2.log
log-level=notice

save-session=/home/wineo/.config/aria2/aria2.session
input-file=/home/wineo/.config/aria2/aria2.session
save-session-interval=60